"""Initial models

Revision ID: 79584c1615d8
Revises: 
Create Date: 2026-04-08 08:40:49.449599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79584c1615d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scam_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('address_type', sa.String(length=20), nullable=False),
    sa.Column('address_raw', sa.String(length=500), nullable=False),
    sa.Column('address_normalized', sa.String(length=500), nullable=False),
    sa.Column('reporter_ip', sa.String(length=45), nullable=True),
    sa.Column('reporter_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scam_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scam_reports_address_normalized'), ['address_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_scam_reports_token'), ['token'], unique=True)

    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('address_type', sa.String(length=20), nullable=False),
    sa.Column('address_raw', sa.String(length=500), nullable=False),
    sa.Column('address_normalized', sa.String(length=500), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.Column('findings_json', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('requester_ip', sa.String(length=45), nullable=True),
    sa.Column('analysis_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scans_address_normalized'), ['address_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_scans_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scans_token'))
        batch_op.drop_index(batch_op.f('ix_scans_address_normalized'))

    op.drop_table('scans')
    with op.batch_alter_table('scam_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scam_reports_token'))
        batch_op.drop_index(batch_op.f('ix_scam_reports_address_normalized'))

    op.drop_table('scam_reports')
    # ### end Alembic commands ###
